In [1]:
import ujson
import pandas

In [5]:
data = pandas.read_json('stargazers_paginated_jiahaog_nativefier.json')
contrib_data = pandas.read_json('nativefier_contrib.json')

In [25]:
contrib_data

,author,total,weeks
0,"{'login': 'krishkumar', 'avatar': 'https://ava...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
1,"{'login': 'Ivshti', 'avatar': 'https://avatars...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
2,"{'login': 'jasonhinkle', 'avatar': 'https://av...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
3,"{'login': 'radarhere', 'avatar': 'https://avat...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
4,"{'login': 'taiyoslime', 'avatar': 'https://ava...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
5,"{'login': 'chentsulin', 'avatar': 'https://ava...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
6,"{'login': 'fearenales', 'avatar': 'https://ava...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
7,"{'login': 'kmelia', 'avatar': 'https://avatars...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
8,"{'login': 'PoziWorld', 'avatar': 'https://avat...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
9,"{'login': 'himynameisdave', 'avatar': 'https:/...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
10,"{'login': 'mmuehlberger', 'avatar': 'https://a...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
11,"{'login': 'starquake', 'avatar': 'https://avat...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
12,"{'login': 'gfpacheco', 'avatar': 'https://avat...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
13,"{'login': 'tengyifei', 'avatar': 'https://avat...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
14,"{'login': 'remixz', 'avatar': 'https://avatars...",1,"[{'d': 7, 'a': 19, 'w': 1426982400, 'c': 1}, {..."
15,"{'login': 'zaggino', 'avatar': 'https://avatar...",2,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
16,"{'login': 'contra', 'avatar': 'https://avatars...",2,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
17,"{'login': 'stefanbuck', 'avatar': 'https://ava...",2,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
18,"{'login': 'mattchue', 'avatar': 'https://avata...",2,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
19,"{'login': 'shama', 'avatar': 'https://avatars2...",2,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
20,"{'login': 'Rameshv', 'avatar': 'https://avatar...",3,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
21,"{'login': 'sindresorhus', 'avatar': 'https://a...",3,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
22,"{'login': 'kfranqueiro', 'avatar': 'https://av...",4,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
23,"{'login': 'jden', 'avatar': 'https://avatars1....",5,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
24,"{'login': 'jenslind', 'avatar': 'https://avata...",6,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
25,"{'login': 'mafintosh', 'avatar': 'https://avat...",7,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
26,"{'login': 'zweicoder', 'avatar': 'https://avat...",10,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
27,"{'login': 'malept', 'avatar': 'https://avatars...",10,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."
28,"{'login': 'maxogden', 'avatar': 'https://avata...",49,"[{'d': 29, 'a': 234, 'w': 1426982400, 'c': 11}..."
29,"{'login': 'jiahaog', 'avatar': 'https://avatar...",224,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'..."

In [26]:
contrib_data["contributor"]=contrib_data.apply(lambda x: x['author']['login'], axis=1)

In [27]:
contrib_data

,author,total,weeks,contributor
0,"{'login': 'krishkumar', 'avatar': 'https://ava...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",krishkumar
1,"{'login': 'Ivshti', 'avatar': 'https://avatars...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",Ivshti
2,"{'login': 'jasonhinkle', 'avatar': 'https://av...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",jasonhinkle
3,"{'login': 'radarhere', 'avatar': 'https://avat...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",radarhere
4,"{'login': 'taiyoslime', 'avatar': 'https://ava...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",taiyoslime
5,"{'login': 'chentsulin', 'avatar': 'https://ava...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",chentsulin
6,"{'login': 'fearenales', 'avatar': 'https://ava...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",fearenales
7,"{'login': 'kmelia', 'avatar': 'https://avatars...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",kmelia
8,"{'login': 'PoziWorld', 'avatar': 'https://avat...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",PoziWorld
9,"{'login': 'himynameisdave', 'avatar': 'https:/...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",himynameisdave
10,"{'login': 'mmuehlberger', 'avatar': 'https://a...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",mmuehlberger
11,"{'login': 'starquake', 'avatar': 'https://avat...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",starquake
12,"{'login': 'gfpacheco', 'avatar': 'https://avat...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",gfpacheco
13,"{'login': 'tengyifei', 'avatar': 'https://avat...",1,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",tengyifei
14,"{'login': 'remixz', 'avatar': 'https://avatars...",1,"[{'d': 7, 'a': 19, 'w': 1426982400, 'c': 1}, {...",remixz
15,"{'login': 'zaggino', 'avatar': 'https://avatar...",2,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",zaggino
16,"{'login': 'contra', 'avatar': 'https://avatars...",2,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",contra
17,"{'login': 'stefanbuck', 'avatar': 'https://ava...",2,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",stefanbuck
18,"{'login': 'mattchue', 'avatar': 'https://avata...",2,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",mattchue
19,"{'login': 'shama', 'avatar': 'https://avatars2...",2,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",shama
20,"{'login': 'Rameshv', 'avatar': 'https://avatar...",3,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",Rameshv
21,"{'login': 'sindresorhus', 'avatar': 'https://a...",3,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",sindresorhus
22,"{'login': 'kfranqueiro', 'avatar': 'https://av...",4,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",kfranqueiro
23,"{'login': 'jden', 'avatar': 'https://avatars1....",5,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",jden
24,"{'login': 'jenslind', 'avatar': 'https://avata...",6,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",jenslind
25,"{'login': 'mafintosh', 'avatar': 'https://avat...",7,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",mafintosh
26,"{'login': 'zweicoder', 'avatar': 'https://avat...",10,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",zweicoder
27,"{'login': 'malept', 'avatar': 'https://avatars...",10,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",malept
28,"{'login': 'maxogden', 'avatar': 'https://avata...",49,"[{'d': 29, 'a': 234, 'w': 1426982400, 'c': 11}...",maxogden
29,"{'login': 'jiahaog', 'avatar': 'https://avatar...",224,"[{'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}, {'...",jiahaog

In [44]:
cs = contrib_data[['weeks','contributor']].set_index('contributor')

In [94]:
contrib_pivoted = cs.weeks.apply(pandas.Series).stack().to_frame().rename(columns={0:"weeks"})

In [89]:
contrib_pivoted

                                                            weeks
contributor
krishkumar  0           {'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}
            1           {'d': 0, 'a': 0, 'w': 1427587200, 'c': 0}
            2           {'d': 0, 'a': 0, 'w': 1428192000, 'c': 0}
            3           {'d': 0, 'a': 0, 'w': 1428796800, 'c': 0}
            4           {'d': 0, 'a': 0, 'w': 1429401600, 'c': 0}
            5           {'d': 0, 'a': 0, 'w': 1430006400, 'c': 0}
            6           {'d': 0, 'a': 0, 'w': 1430611200, 'c': 0}
            7           {'d': 0, 'a': 0, 'w': 1431216000, 'c': 0}
            8           {'d': 0, 'a': 0, 'w': 1431820800, 'c': 0}
            9           {'d': 0, 'a': 0, 'w': 1432425600, 'c': 0}
            10          {'d': 0, 'a': 0, 'w': 1433030400, 'c': 0}
            11          {'d': 0, 'a': 0, 'w': 1433635200, 'c': 0}
            12          {'d': 0, 'a': 0, 'w': 1434240000, 'c': 0}
            13          {'d': 0, 'a': 0, 'w': 1434844800, 'c': 0}
            14          {'d': 0, 'a': 0, 'w': 1435449600, 'c': 0}
            15          {'d': 0, 'a': 0, 'w': 1436054400, 'c': 0}
            16          {'d': 0, 'a': 0, 'w': 1436659200, 'c': 0}
            17          {'d': 0, 'a': 0, 'w': 1437264000, 'c': 0}
            18          {'d': 0, 'a': 0, 'w': 1437868800, 'c': 0}
            19          {'d': 0, 'a': 0, 'w': 1438473600, 'c': 0}
            20          {'d': 0, 'a': 0, 'w': 1439078400, 'c': 0}
            21          {'d': 0, 'a': 0, 'w': 1439683200, 'c': 0}
            22          {'d': 0, 'a': 0, 'w': 1440288000, 'c': 0}
            23          {'d': 0, 'a': 0, 'w': 1440892800, 'c': 0}
            24          {'d': 0, 'a': 0, 'w': 1441497600, 'c': 0}
            25          {'d': 0, 'a': 0, 'w': 1442102400, 'c': 0}
            26          {'d': 0, 'a': 0, 'w': 1442707200, 'c': 0}
            27          {'d': 0, 'a': 0, 'w': 1443312000, 'c': 0}
            28          {'d': 0, 'a': 0, 'w': 1443916800, 'c': 0}
            29          {'d': 0, 'a': 0, 'w': 1444521600, 'c': 0}
...                                                           ...
jiahaog     15     {'d': 328, 'a': 609, 'w': 1436054400, 'c': 36}
            16          {'d': 0, 'a': 0, 'w': 1436659200, 'c': 0}
            17          {'d': 0, 'a': 0, 'w': 1437264000, 'c': 0}
            18          {'d': 0, 'a': 0, 'w': 1437868800, 'c': 0}
            19          {'d': 0, 'a': 0, 'w': 1438473600, 'c': 0}
            20          {'d': 0, 'a': 0, 'w': 1439078400, 'c': 0}
            21          {'d': 0, 'a': 0, 'w': 1439683200, 'c': 0}
            22          {'d': 0, 'a': 0, 'w': 1440288000, 'c': 0}
            23          {'d': 0, 'a': 0, 'w': 1440892800, 'c': 0}
            24          {'d': 0, 'a': 0, 'w': 1441497600, 'c': 0}
            25          {'d': 0, 'a': 0, 'w': 1442102400, 'c': 0}
            26          {'d': 0, 'a': 0, 'w': 1442707200, 'c': 0}
            27          {'d': 0, 'a': 0, 'w': 1443312000, 'c': 0}
            28          {'d': 0, 'a': 0, 'w': 1443916800, 'c': 0}
            29          {'d': 0, 'a': 0, 'w': 1444521600, 'c': 0}
            30          {'d': 0, 'a': 0, 'w': 1445126400, 'c': 0}
            31          {'d': 0, 'a': 0, 'w': 1445731200, 'c': 0}
            32          {'d': 0, 'a': 0, 'w': 1446336000, 'c': 0}
            33          {'d': 0, 'a': 0, 'w': 1446940800, 'c': 0}
            34          {'d': 0, 'a': 0, 'w': 1447545600, 'c': 0}
            35          {'d': 0, 'a': 0, 'w': 1448150400, 'c': 0}
            36          {'d': 0, 'a': 0, 'w': 1448755200, 'c': 0}
            37          {'d': 0, 'a': 0, 'w': 1449360000, 'c': 0}
            38          {'d': 0, 'a': 0, 'w': 1449964800, 'c': 0}
            39          {'d': 0, 'a': 0, 'w': 1450569600, 'c': 0}
            40          {'d': 0, 'a': 0, 'w': 1451174400, 'c': 0}
            41          {'d': 0, 'a': 0, 'w': 1451779200, 'c': 0}
            42          {'d': 0, 'a': 0, 'w': 1452384000, 'c': 0}
            43  {'d': 3691, 'a': 3477, 'w': 1452988800, 'c': 107}
            44   {'d': 1286, 'a': 2276, 'w': 1453593600, 'c': 81}

[1350 rows x 1 columns]

In [95]:
contrib_pivoted["time"]=contrib_pivoted.apply(lambda x: x['weeks']['w'], axis=1)
contrib_pivoted["added"]=contrib_pivoted.apply(lambda x: x['weeks']['a'], axis=1)
contrib_pivoted["deleted"]=contrib_pivoted.apply(lambda x: x['weeks']['d'], axis=1)
contrib_pivoted["commits"]=contrib_pivoted.apply(lambda x: x['weeks']['c'], axis=1)

In [91]:
contrib_pivoted

                                                            weeks      weeksd  \
contributor
krishkumar  0           {'d': 0, 'a': 0, 'w': 1426982400, 'c': 0}  1426982400
            1           {'d': 0, 'a': 0, 'w': 1427587200, 'c': 0}  1427587200
            2           {'d': 0, 'a': 0, 'w': 1428192000, 'c': 0}  1428192000
            3           {'d': 0, 'a': 0, 'w': 1428796800, 'c': 0}  1428796800
            4           {'d': 0, 'a': 0, 'w': 1429401600, 'c': 0}  1429401600
            5           {'d': 0, 'a': 0, 'w': 1430006400, 'c': 0}  1430006400
            6           {'d': 0, 'a': 0, 'w': 1430611200, 'c': 0}  1430611200
            7           {'d': 0, 'a': 0, 'w': 1431216000, 'c': 0}  1431216000
            8           {'d': 0, 'a': 0, 'w': 1431820800, 'c': 0}  1431820800
            9           {'d': 0, 'a': 0, 'w': 1432425600, 'c': 0}  1432425600
            10          {'d': 0, 'a': 0, 'w': 1433030400, 'c': 0}  1433030400
            11          {'d': 0, 'a': 0, 'w': 1433635200, 'c': 0}  1433635200
            12          {'d': 0, 'a': 0, 'w': 1434240000, 'c': 0}  1434240000
            13          {'d': 0, 'a': 0, 'w': 1434844800, 'c': 0}  1434844800
            14          {'d': 0, 'a': 0, 'w': 1435449600, 'c': 0}  1435449600
            15          {'d': 0, 'a': 0, 'w': 1436054400, 'c': 0}  1436054400
            16          {'d': 0, 'a': 0, 'w': 1436659200, 'c': 0}  1436659200
            17          {'d': 0, 'a': 0, 'w': 1437264000, 'c': 0}  1437264000
            18          {'d': 0, 'a': 0, 'w': 1437868800, 'c': 0}  1437868800
            19          {'d': 0, 'a': 0, 'w': 1438473600, 'c': 0}  1438473600
            20          {'d': 0, 'a': 0, 'w': 1439078400, 'c': 0}  1439078400
            21          {'d': 0, 'a': 0, 'w': 1439683200, 'c': 0}  1439683200
            22          {'d': 0, 'a': 0, 'w': 1440288000, 'c': 0}  1440288000
            23          {'d': 0, 'a': 0, 'w': 1440892800, 'c': 0}  1440892800
            24          {'d': 0, 'a': 0, 'w': 1441497600, 'c': 0}  1441497600
            25          {'d': 0, 'a': 0, 'w': 1442102400, 'c': 0}  1442102400
            26          {'d': 0, 'a': 0, 'w': 1442707200, 'c': 0}  1442707200
            27          {'d': 0, 'a': 0, 'w': 1443312000, 'c': 0}  1443312000
            28          {'d': 0, 'a': 0, 'w': 1443916800, 'c': 0}  1443916800
            29          {'d': 0, 'a': 0, 'w': 1444521600, 'c': 0}  1444521600
...                                                           ...         ...
jiahaog     15     {'d': 328, 'a': 609, 'w': 1436054400, 'c': 36}  1436054400
            16          {'d': 0, 'a': 0, 'w': 1436659200, 'c': 0}  1436659200
            17          {'d': 0, 'a': 0, 'w': 1437264000, 'c': 0}  1437264000
            18          {'d': 0, 'a': 0, 'w': 1437868800, 'c': 0}  1437868800
            19          {'d': 0, 'a': 0, 'w': 1438473600, 'c': 0}  1438473600
            20          {'d': 0, 'a': 0, 'w': 1439078400, 'c': 0}  1439078400
            21          {'d': 0, 'a': 0, 'w': 1439683200, 'c': 0}  1439683200
            22          {'d': 0, 'a': 0, 'w': 1440288000, 'c': 0}  1440288000
            23          {'d': 0, 'a': 0, 'w': 1440892800, 'c': 0}  1440892800
            24          {'d': 0, 'a': 0, 'w': 1441497600, 'c': 0}  1441497600
            25          {'d': 0, 'a': 0, 'w': 1442102400, 'c': 0}  1442102400
            26          {'d': 0, 'a': 0, 'w': 1442707200, 'c': 0}  1442707200
            27          {'d': 0, 'a': 0, 'w': 1443312000, 'c': 0}  1443312000
            28          {'d': 0, 'a': 0, 'w': 1443916800, 'c': 0}  1443916800
            29          {'d': 0, 'a': 0, 'w': 1444521600, 'c': 0}  1444521600
            30          {'d': 0, 'a': 0, 'w': 1445126400, 'c': 0}  1445126400
            31          {'d': 0, 'a': 0, 'w': 1445731200, 'c': 0}  1445731200
            32          {'d': 0, 'a': 0, 'w': 1446336000, 'c': 0}  1446336000
            33          {'d': 0, 'a': 0, 'w': 1446940800, 'c': 0}  1446940800
            34          {'d': 0, 'a': 0, 'w': 1447545600, 'c': 0}  1447545600
            35          {'d': 0, 'a': 0, 'w': 1448150400, 'c': 0}  1448150400
            36          {'d': 0, 'a': 0, 'w': 1448755200, 'c': 0}  1448755200
            37          {'d': 0, 'a': 0, 'w': 1449360000, 'c': 0}  1449360000
            38          {'d': 0, 'a': 0, 'w': 1449964800, 'c': 0}  1449964800
            39          {'d': 0, 'a': 0, 'w': 1450569600, 'c': 0}  1450569600
            40          {'d': 0, 'a': 0, 'w': 1451174400, 'c': 0}  1451174400
            41          {'d': 0, 'a': 0, 'w': 1451779200, 'c': 0}  1451779200
            42          {'d': 0, 'a': 0, 'w': 1452384000, 'c': 0}  1452384000
            43  {'d': 3691, 'a': 3477, 'w': 1452988800, 'c': 107}  1452988800
            44   {'d': 1286, 'a': 2276, 'w': 1453593600, 'c': 81}  1453593600

                added  deleted  commits
contributor
krishkumar  0       0        0        0
            1       0        0        0
            2       0        0        0
            3       0        0        0
            4       0        0        0
            5       0        0        0
            6       0        0        0
            7       0        0        0
            8       0        0        0
            9       0        0        0
            10      0        0        0
            11      0        0        0
            12      0        0        0
            13      0        0        0
            14      0        0        0
            15      0        0        0
            16      0        0        0
            17      0        0        0
            18      0        0        0
            19      0        0        0
            20      0        0        0
            21      0        0        0
            22      0        0        0
            23      0        0        0
            24      0        0        0
            25      0        0        0
            26      0        0        0
            27      0        0        0
            28      0        0        0
            29      0        0        0
...               ...      ...      ...
jiahaog     15    609      328       36
            16      0        0        0
            17      0        0        0
            18      0        0        0
            19      0        0        0
            20      0        0        0
            21      0        0        0
            22      0        0        0
            23      0        0        0
            24      0        0        0
            25      0        0        0
            26      0        0        0
            27      0        0        0
            28      0        0        0
            29      0        0        0
            30      0        0        0
            31      0        0        0
            32      0        0        0
            33      0        0        0
            34      0        0        0
            35      0        0        0
            36      0        0        0
            37      0        0        0
            38      0        0        0
            39      0        0        0
            40      0        0        0
            41      0        0        0
            42      0        0        0
            43   3477     3691      107
            44   2276     1286       81

[1350 rows x 5 columns]

In [96]:
data.to_csv("test_stars.csv")
contrib_data.to_csv("test_natifier_data.csv")
contrib_pivoted.to_csv("natifier_data.csv")